In [1]:
# Imports
import os
import matplotlib.pyplot as plt
import xmlparse

import pandas as pd
import numpy as np

from xmlparse import loadRef

"""
To-do:

- extract components from archetypes (point list + frac dist)
-- 
- remove duplicates
- save in database
"""

'\nTo-do:\n\n- extract components from archetypes (point list + frac dist)\n-- \n- remove duplicates\n- save in database\n'

In [2]:
components = []

ref_dir = "Reference"
subdirs = os.listdir(ref_dir)
subdirs.sort()
for subdir in subdirs:
    f_names = os.listdir(f'{ref_dir}/{subdir}')
    f_names.sort()
    f_names = [j for i, j in enumerate(f_names) if j != '.ipynb_checkpoints'] # ignores checkpoints
    for f_name in f_names:
        file = f_name[:4]
        #"""
        stroke_list, frac_dists, _ = loadRef(file, ref_dir)
        for stroke, frac_dist in zip(stroke_list, frac_dists):
            not_copy = True
            for i in range(0, len(components)):
                """
                print(i)
                print(stroke)
                print(components[i][0])
                print(stroke == components[i][0])
                """
                x = [all(a != b) for a, b in zip(stroke, components[i][0])]
                """
                print(x)
                print("length")
                print(len(stroke))
                print(len(components[i][0]))
                """
                if (all(x) and len(stroke)==len(components[i][0])):
                    not_copy = False
                #"""
            if not_copy:
                duo = [stroke, frac_dist]
                components.append(duo)
                
                #"""
        #"""
print(components)
print(len(components))


[[array([[360., 350.],
       [ 40.,  30.],
       [  0., 130.]]), array([0.        , 0.80775907, 1.        ])], [array([[190.     , 340.     ],
       [173.625  , 329.96875],
       [155.5    , 321.375  ],
       [135.625  , 314.21875],
       [114.     , 308.5    ],
       [ 90.625  , 304.21875],
       [ 65.5    , 301.375  ],
       [ 38.625  , 299.96875],
       [ 10.     , 300.     ]]), array([0.        , 0.10250454, 0.20957733, 0.32233485, 0.4417342 ,
       0.56858225, 0.70355233, 0.84720362, 1.        ])], [array([[150., 410.],
       [  0., 260.]]), array([0., 1.])], [array([[360., 360.],
       [360.,   0.],
       [150.,   0.]]), array([0.        , 0.63157895, 1.        ])], [array([[460., 180.],
       [  0., 180.]]), array([0., 1.])], [array([[400., 250.],
       [150.,   0.],
       [  0., 150.]]), array([0.   , 0.625, 1.   ])], [array([[360., 100.],
       [  0., 100.],
       [  0., 310.]]), array([0.        , 0.63157895, 1.        ])], [array([[360., 270.],
       [  0

In [3]:
for co in components:
    print(co[0])
    print()

[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]

[[190.      340.     ]
 [173.625   329.96875]
 [155.5     321.375  ]
 [135.625   314.21875]
 [114.      308.5    ]
 [ 90.625   304.21875]
 [ 65.5     301.375  ]
 [ 38.625   299.96875]
 [ 10.      300.     ]]

[[150. 410.]
 [  0. 260.]]

[[360. 360.]
 [360.   0.]
 [150.   0.]]

[[460. 180.]
 [  0. 180.]]

[[400. 250.]
 [150.   0.]
 [  0. 150.]]

[[360. 100.]
 [  0. 100.]
 [  0. 310.]]

[[360. 270.]
 [  0. 270.]]

[[  0. 360.]
 [  0. 150.]]

[[ 30.     340.    ]
 [380.     340.    ]
 [361.6875 302.1875]
 [338.25   266.25  ]
 [309.6875 232.1875]
 [276.     200.    ]
 [237.1875 169.6875]
 [193.25   141.25  ]
 [144.1875 114.6875]
 [ 90.      90.    ]]

[[  0.        0.     ]
 [ 80.      110.     ]
 [ 86.28125  88.46875]
 [ 96.125    69.875  ]
 [109.53125  54.21875]
 [126.5      41.5    ]
 [147.03125  31.71875]
 [171.125    24.875  ]
 [198.78125  20.96875]
 [230.       20.     ]
 [440.       20.     ]]

[[  0. 340.]
 [  0.   0.]]

[[  0. 340.]
 [370. 

In [4]:
print(type(components[0][0]))
# list -> list -> ndarray
print(type(components[0][1]))
# list -> list -> list

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
comp_array = [[]]*len(components)
frac_array = [[]]*len(components)
index = 0
for comp in components:
    comp_array[index] = comp[0]
    frac_array[index] = comp[1]
    index = index +1

comp_array = np.array(comp_array, dtype=object).T
frac_array = np.array(frac_array, dtype=object).T
print(comp_array)
print(frac_array)

[array([[360., 350.],
       [ 40.,  30.],
       [  0., 130.]])
 array([[190.     , 340.     ],
       [173.625  , 329.96875],
       [155.5    , 321.375  ],
       [135.625  , 314.21875],
       [114.     , 308.5    ],
       [ 90.625  , 304.21875],
       [ 65.5    , 301.375  ],
       [ 38.625  , 299.96875],
       [ 10.     , 300.     ]])
 array([[150., 410.],
       [  0., 260.]])
 array([[360., 360.],
       [360.,   0.],
       [150.,   0.]])
 array([[460., 180.],
       [  0., 180.]])
 array([[400., 250.],
       [150.,   0.],
       [  0., 150.]])
 array([[360., 100.],
       [  0., 100.],
       [  0., 310.]])
 array([[360., 270.],
       [  0., 270.]])
 array([[  0., 360.],
       [  0., 150.]])
 array([[ 30.    , 340.    ],
       [380.    , 340.    ],
       [361.6875, 302.1875],
       [338.25  , 266.25  ],
       [309.6875, 232.1875],
       [276.    , 200.    ],
       [237.1875, 169.6875],
       [193.25  , 141.25  ],
       [144.1875, 114.6875],
       [ 90.    ,  90

In [6]:
comp_data = pd.DataFrame.from_records([comp_array, frac_array], nrows=len(components), index=["Stroke Point List", "Fractional Distances"])
#print(frac_array)
comp_data.head()

0   \
Stroke Point List     [[360.0, 350.0], [40.0, 30.0], [0.0, 130.0]]   
Fractional Distances                [0.0, 0.8077590689568892, 1.0]   

                                                                     1   \
Stroke Point List     [[190.0, 340.0], [173.625, 329.96875], [155.5,...   
Fractional Distances  [0.0, 0.10250454099094851, 0.20957733128388562...   

                                                  2   \
Stroke Point List     [[150.0, 410.0], [0.0, 260.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                                3   \
Stroke Point List     [[360.0, 360.0], [360.0, 0.0], [150.0, 0.0]]   
Fractional Distances                 [0.0, 0.631578947368421, 1.0]   

                                                  4   \
Stroke Point List     [[460.0, 180.0], [0.0, 180.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                                5   \
Stroke Point List     [[400.0, 250.0], [150.0, 0.0], [0.0, 150.0]]   
Fractional Distances                             [0.0, 0.625, 1.0]   

                                                                6   \
Stroke Point List     [[360.0, 100.0], [0.0, 100.0], [0.0, 310.0]]   
Fractional Distances                 [0.0, 0.631578947368421, 1.0]   

                                                  7   \
Stroke Point List     [[360.0, 270.0], [0.0, 270.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                8   \
Stroke Point List     [[0.0, 360.0], [0.0, 150.0]]   
Fractional Distances                    [0.0, 1.0]   

                                                                     9   \
Stroke Point List     [[30.0, 340.0], [380.0, 340.0], [361.6875, 302...   
Fractional Distances  [0.0, 0.4711355182994917, 0.5276899309222032, ...   

                                 ...              \
Stroke Point List                ...               
Fractional Distances             ...               

                                                             36  \
Stroke Point List     [[80.0, 470.0], [80.0, 0.0], [0.0, 40.0]]   
Fractional Distances             [0.0, 0.8401217568013338, 1.0]   

                                               37  \
Stroke Point List     [[0.0, 410.0], [0.0, 60.0]]   
Fractional Distances                   [0.0, 1.0]   

                                                                     38  \
Stroke Point List     [[190.0, 150.0], [190.6875, 135.65625], [189.7...   
Fractional Distances  [0.0, 0.11097654938557544, 0.22350832315518973...   

                                                                     39  \
Stroke Point List     [[70.0, 340.0], [92.9375, 314.78125], [110.75,...   
Fractional Distances  [0.0, 0.07912092785520795, 0.16041023241997646...   

                                                                     40  \
Stroke Point List     [[200.0, 330.0], [187.75, 309.125], [172.0, 29...   
Fractional Distances  [0.0, 0.24039811462418845, 0.4826612443022861,...   

                                                                     41  \
Stroke Point List     [[140.0, 220.0], [157.875, 205.0], [166.71875,...   
Fractional Distances  [0.0, 0.20289105130173543, 0.3149498222520564,...   

                                                                     42  \
Stroke Point List     [[0.0, 0.0], [80.0, 70.0], [89.75, 55.71875], ...   
Fractional Distances  [0.0, 0.21370108704081714, 0.24846391988979122...   

                                                                     43  \
Stroke Point List     [[0.0, 0.0], [70.0, 60.0], [79.6875, 47.625], ...   
Fractional Distances  [0.0, 0.18518584808621436, 0.21675308036610935...   

                                              44                          45  
Stroke Point List     [[0.0, 430.0], [0.0, 0.0]]  [[0.0, 330.0], [0.0, 0.0]]  
Fractional Distances                  [0.0, 1.0]                 

In [7]:
comp_data.to_csv("ComponentDataV2.csv")