In [1]:
# Imports
import os
import matplotlib.pyplot as plt
import xmlparse

import pandas as pd
import numpy as np

from xmlparse import loadRef

"""
To-do:

- extract components from archetypes (point list + frac dist)
-- 
- remove duplicates
- save in database
"""

'\nTo-do:\n\n- extract components from archetypes (point list + frac dist)\n-- \n- remove duplicates\n- save in database\n'

In [2]:
components = []

ref_dir = "Reference"
subdirs = os.listdir(ref_dir)
subdirs.sort()
for subdir in subdirs:
    f_names = os.listdir(f'{ref_dir}/{subdir}')
    f_names.sort()
    f_names = [j for i, j in enumerate(f_names) if j != '.ipynb_checkpoints'] # ignores checkpoints
    for f_name in f_names:
        file = f_name[:4]
        #"""
        stroke_list, frac_dists, _ = loadRef(file, ref_dir)
        for stroke, frac_dist in zip(stroke_list, frac_dists):
            not_copy = True
            for i in range(0, len(components)):
                print(i)
                #print(stroke)
                print(components[i][0])
                #"""
                #print(stroke == components[i][0])
                x = [all(a != b) for a, b in zip(stroke, components[i][0])]
                print(x)
                if (all(x)):
                    not_copy = False
                #"""
            if not_copy:
                duo = [stroke, frac_dist]
                components.append(duo)
                #"""
        #"""
print(components)


0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, False]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[False, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[False, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[False, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]


 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[False, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [28

[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[False, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True

 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[

[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[False, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[Tr

0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, False]
1
[[ 30. 290.]
 [290.  30.]]
[False, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]


6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [29

[True, True]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[True, True]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[True, True]
10
[[170.  30.]
 [450.  30.]]

[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[False, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[True, True]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[False, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[True, True]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]

 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[False, False]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, True]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [230.  30.]]
[True, True]
10
[[170.  30.]
 [450.  30.]]
[True, True]
0
[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]
[True, True]
1
[[ 30. 290.]
 [290.  30.]]
[True, True]
2
[[ 60. 350.]
 [380.  30.]]
[True, True]
3
[[280. 410.]
 [280.  30.]]
[True, True]
4
[[230. 280.]
 [230.  30.]]
[True, True]
5
[[220. 130.]
 [220.  30.]]
[True, True]
6
[[300. 160.]
 [300.  30.]]
[True, True]
7
[[140.  30.]
 [460.  30.]]
[True, False]
8
[[280. 190.]
 [280.  30.]]
[True, True]
9
[[230. 420.]
 [2

In [3]:
for co in components:
    print(co[0])
    print()

[[360. 350.]
 [ 40.  30.]
 [  0. 130.]]

[[ 30. 290.]
 [290.  30.]]

[[ 60. 350.]
 [380.  30.]]

[[280. 410.]
 [280.  30.]]

[[230. 280.]
 [230.  30.]]

[[220. 130.]
 [220.  30.]]

[[300. 160.]
 [300.  30.]]

[[140.  30.]
 [460.  30.]]

[[280. 190.]
 [280.  30.]]

[[230. 420.]
 [230.  30.]]

[[170.  30.]
 [450.  30.]]



In [4]:
print(type(components[0][0]))
# list -> list -> ndarray
print(type(components[0][1]))
# list -> list -> list

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
comp_array = [[]]*len(components)
frac_array = [[]]*len(components)
index = 0
for comp in components:
    comp_array[index] = comp[0]
    frac_array[index] = comp[1]
    index = index +1

comp_array = np.array(comp_array, dtype=object).T
frac_array = np.array(frac_array, dtype=object).T
print(comp_array)
print(frac_array)

[array([[360., 350.],
       [ 40.,  30.],
       [  0., 130.]])
 array([[ 30., 290.],
       [290.,  30.]])
 array([[ 60., 350.],
       [380.,  30.]])
 array([[280., 410.],
       [280.,  30.]])
 array([[230., 280.],
       [230.,  30.]])
 array([[220., 130.],
       [220.,  30.]])
 array([[300., 160.],
       [300.,  30.]])
 array([[140.,  30.],
       [460.,  30.]])
 array([[280., 190.],
       [280.,  30.]])
 array([[230., 420.],
       [230.,  30.]])
 array([[170.,  30.],
       [450.,  30.]])]
[array([0.        , 0.80775907, 1.        ]) array([0., 1.])
 array([0., 1.]) array([0., 1.]) array([0., 1.]) array([0., 1.])
 array([0., 1.]) array([0., 1.]) array([0., 1.]) array([0., 1.])
 array([0., 1.])]


In [6]:
comp_data = pd.DataFrame.from_records([comp_array, frac_array], nrows=len(components), index=["Stroke Point List", "Fractional Distances"])
#print(frac_array)
comp_data.head()

0   \
Stroke Point List     [[360.0, 350.0], [40.0, 30.0], [0.0, 130.0]]   
Fractional Distances                [0.0, 0.8077590689568892, 1.0]   

                                                  1   \
Stroke Point List     [[30.0, 290.0], [290.0, 30.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                  2   \
Stroke Point List     [[60.0, 350.0], [380.0, 30.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                   3   \
Stroke Point List     [[280.0, 410.0], [280.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                   4   \
Stroke Point List     [[230.0, 280.0], [230.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                   5   \
Stroke Point List     [[220.0, 130.0], [220.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                   6   \
Stroke Point List     [[300.0, 160.0], [300.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                  7   \
Stroke Point List     [[140.0, 30.0], [460.0, 30.0]]   
Fractional Distances                      [0.0, 1.0]   

                                                   8   \
Stroke Point List     [[280.0, 190.0], [280.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                   9   \
Stroke Point List     [[230.0, 420.0], [230.0, 30.0]]   
Fractional Distances                       [0.0, 1.0]   

                                                  10  
Stroke Point List     [[170.0, 30.0], [450.0, 30.0]]  
Fractional Distances                      [0.0, 1.0]

In [8]:
comp_data.to_csv("ComponentDataV1.csv")