# Heuristic V1

In [1]:
import pickle
import numpy as np
import StrokeDef
import xmlparse
import xmltodict
import score_strokes

from StrokeDef import loadStrokeDict
from xmlparse import loadGeometryBases
from score_strokes import strokeError, strokeErrorScaled

"""

"""

'\n\n'

## Comparing Gene Strokes to Archetypal Strokes

In [50]:
archetypal_strokes = loadStrokeDict()
#for key in archetypal_strokes:
    #print(archetypal_strokes[key].arial)

"""

Parameters:
    gene - .gene file
    OR list of strokes, total num of strokes

Return Value:
    total_array - an array containing the total percentages
    
    percent_arrays - a 2D array
"""
#def getGeneStrokePercentages():

    # char_data = loadGeometryBases(data_dir)



"""
Gives a list of scores for how well a given gene stroke matches each of the archetypal strokes

Parameters:
    g_points - a list of the points in the gene stroke
    g_frac_prog - a list of fractional progress of each point in the gene stroke
    
Return Value:
    strokePercentages - an array containing 51 elements, each representing how well geneStroke
    compares to each of the archetypal strokes
"""
def getStrokePercentage(g_points, g_frac_prog):
    
    errors = [] # need to convert errors to scores, what is maximum error?  
    for key in archetypal_strokes:
        stroke_arial = archetypal_strokes[key].arial
        points = convertToPointList(stroke_arial)
        frac_prog = getFractionalProgress(points)
        print("frac prog")
        print(len(frac_prog))
        print(frac_prog)
        error = strokeErrorScaled(g_points, points, g_frac_prog, frac_prog)
        errors.append(error)
    return errors    
    

# unpickle, figure out the format of StrokeType object
# get the p_stroke and p_ref necessary for strokeError
# use strokeErrorScaled?

"""
Parameters:
    stroke_arial - arial data from an archetypal stroke to be converted
    
Return Value:
    point_list - an array of pairs, stroke_arial converted to the point list format of a gene stroke
"""
def convertToPointList(stroke_arial):
    point_list = []
    for segment in stroke_arial:
        for point in segment:
            point_list.append(point)
        print(point_list)
    return point_list

def getFractionalProgress(point_list):
    dists = [0]
    for i in range(len(point_list)-1):
        dists.append(np.linalg.norm((point_list[i]-point_list[i+1]))+dists[-1])
    dists = np.array(dists)
    #print(dists)
    #print(dists.max())
    dists /= dists.max()
    print("hi")
    print(dists)
    #frac_dists.append(dists)
    #print("hello")
    #print(frac_dists)
    return dists

"""
"""


"""
*Might already be a pre-existing function for this*
Makes it so that the elements of a given list sum to 1,
by dividing each element by the sum of all the elements

Parameters:
    list - list to be manipulated

Return value
    stand_list - list whose elements sum to 1
"""
#def sumToOne()

'\n*Might already be a pre-existing function for this*\nMakes it so that the elements of a given list sum to 1,\nby dividing each element by the sum of all the elements\n\nParameters:\n    list - list to be manipulated\n\nReturn value\n    stand_list - list whose elements sum to 1\n'

## Comparing Gene Stroke Percentage to Archetype Stroke Counts

In [3]:
"""
Compares the stroke percentages of a gene to the stroke counts of every archetype in order to
find the top 100 archetypes that most closely resemble the gene

Parameters:
    geneStrokePercents - an array containing the total percentages
    corresponding to the number of archetypal strokes present in the gene
    
    numStrokes - number of strokes contained in the gene

Return Value:
    archetype_matches - a list of the top 50 archetypes whose stroke counts most closely match the gene's stroke percentages

"""
def strokeCountComparison()

SyntaxError: invalid syntax (<ipython-input-3-a928a5df63e4>, line 15)

## Check Archetypes for Highest Score

In [ ]:
"""
IDEAS:
"""

In [51]:
# Test archetypal stroke data
stroke_name = "HZZZG"
archetypal_strokes = loadStrokeDict()
stroke_arial = archetypal_strokes[stroke_name].arial
print(stroke_arial)
points = convertToPointList(stroke_arial)
frac_prog = getFractionalProgress(stroke_arial)
print("hello")
print(frac_prog)

[[[0.   0.  ]
  [0.65 0.  ]
  [0.65 0.  ]]

 [[0.65 0.  ]
  [0.3  0.5 ]
  [0.3  0.5 ]]

 [[0.3  0.5 ]
  [0.4  0.35]
  [0.5  0.35]]

 [[0.5  0.35]
  [0.75 0.35]
  [0.75 0.35]]

 [[0.75 0.35]
  [0.65 1.  ]
  [0.65 1.  ]]

 [[0.65 1.  ]
  [0.3  0.9 ]
  [0.3  0.9 ]]]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.3, 0.5]), array([0.3, 0.5])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.3, 0.5]), array([0.3, 0.5]), array([0.3, 0.5]), array([0.4 , 0.35]), array([0.5 , 0.35])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.3, 0.5]), array([0.3, 0.5]), array([0.3, 0.5]), array([0.4 , 0.35]), array([0.5 , 0.35]), array([0.5 , 0.35]), array([0.75, 0.35]), array([0.75, 0.35])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.3, 0.5]), array([0.3, 0.5]), array([0.3, 0.5

In [54]:
# Test getStrokePercentage()

# problems with formatting

# arch array 2x2
# gene list 4x2
# center ref 1x2
# center stroke 1x2
# center shift 2x2

data_dir = "NewGenes"
char_data = loadGeometryBases(data_dir)
g_data, _, base_data, stroke_sets, _, f_names = char_data
p_list = []
for (gl, bases, stroke_set, f_name) in zip(g_data, base_data, stroke_sets, f_names):
        g, l = gl
        print()
        print(l)
        print()
        for g_points, g_frac in zip(g, l):
            print("g_points")
            print(len(g_points))
            print(g_points)
            print()
            print(g_frac)
            p_list.append(getStrokePercentage(g_points, g_frac))
print()
print()
print("Percentages:")
print(p_list)


segment
[[ 0.         13.89941493]
 [ 3.67516168 20.42345569]
 [ 5.90425992 24.38048643]
 [ 9.57942159 30.90452719]]
dists
[0, 7.48798511978283]
dists
[0, 7.48798511978283, 12.029677674403114]
dists
[0, 7.48798511978283, 12.029677674403114, 19.517662794185945]

segment
[[11.80851983 26.94749645]
 [11.80851983 11.73575608]
 [11.80851983  6.13966954]
 [11.80851983  0.54358299]]
dists
[0, 15.211740365397484]
dists
[0, 15.211740365397484, 20.807826910264986]
dists
[0, 15.211740365397484, 20.807826910264986, 26.403913455132493]

segment
[[16.26671631  0.        ]
 [24.83588492  0.        ]
 [27.98830587  0.        ]
 [31.14072683  0.        ]]
dists
[0, 8.569168608932866]
dists
[0, 8.569168608932866, 11.721589568090959]
dists
[0, 8.569168608932866, 11.721589568090959, 14.874010527249052]

segment
[[20.60275406  1.6390558 ]
 [20.60275406  7.23514235]
 [20.60275406 22.44688271]
 [22.8318523  26.40391346]
 [22.8318523  32.        ]]
dists
[0, 5.596086544867509]
dists
[0, 5.596086544867509, 20

hi
[0.         0.73879613 0.73879613 0.73879613 0.8850703  1.        ]
frac prog
6
[0.         0.73879613 0.73879613 0.73879613 0.8850703  1.        ]
start stroke error
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]), array([0.86, 0.14]), array([0.75, 0.25])]

[[ 0.         13.89941493]
 [ 3.67516168 20.42345569]
 [ 5.90425992 24.38048643]
 [ 9.57942159 30.90452719]]

[0.76833333 0.065     ]

[ 4.7897108  22.40197106]
center
[ -4.02137746 -22.33697106]
32.54514939564974
[array([0.22501403, 0.        ]), array([0.5, 0. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 1.        ])]
hi
[0.         0.17741351 0.17741351 0.82258649 0.82258649 1.        ]
frac prog
6
[0.         0.17741351 0.17741351 0.82258649 0.82258649 1.        ]
start stroke error
[array([0.22501403, 0.        ]), array([0.5, 0

center
[-11.630236   -10.52433482]
34.340165158095466
[array([0. , 0.5]), array([0.034, 0.49 ]), array([0.126, 0.331]), array([0.228, 0.029])]
[array([0. , 0.5]), array([0.034, 0.49 ]), array([0.126, 0.331]), array([0.228, 0.029]), array([0. , 0.5]), array([0.034, 0.51 ]), array([0.126, 0.669]), array([0.228, 0.971])]
hi
[0.         0.02216281 0.13704022 0.33637996 0.66362004 0.68578284
 0.80066026 1.        ]
frac prog
8
[0.         0.02216281 0.13704022 0.33637996 0.66362004 0.68578284
 0.80066026 1.        ]
start stroke error
[array([0. , 0.5]), array([0.034, 0.49 ]), array([0.126, 0.331]), array([0.228, 0.029]), array([0. , 0.5]), array([0.034, 0.51 ]), array([0.126, 0.669]), array([0.228, 0.971])]

[[11.80851983 26.94749645]
 [11.80851983 11.73575608]
 [11.80851983  6.13966954]
 [11.80851983  0.54358299]]

[0.097 0.5  ]

[11.80851983 11.34162626]
center
[-11.71151983 -10.84162626]
62.115092122303594
[array([0.5, 1. ]), array([0.5, 0. ])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start strok

[array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.3, 1. ])]
hi
[0.         0.83333333 0.83333333 1.        ]
frac prog
4
[0.         0.83333333 0.83333333 1.        ]
start stroke error
[array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.3, 1. ])]

[[16.26671631  0.        ]
 [24.83588492  0.        ]
 [27.98830587  0.        ]
 [31.14072683  0.        ]]

[0.45 0.75]

[25.05790848  0.        ]
center
[-24.60790848   0.75      ]
21.177661166483805
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5])]
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5])]
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([0.94 , 0.984]), array([0.868, 0.917]), array([0.52, 0.85])]
hi
[0.         0.20488048 0.20488048 0.20488048 0.204

[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ]), array([0.125, 1.   ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]

[[20.60275406  1.6390558 ]
 [20.60275406  7.23514235]
 [20.60275406 22.44688271]
 [22.8318523  26.40391346]
 [22.8318523  32.        ]]

[0.12625 0.7715 ]

[21.49439336 17.94499886]
center
[-21.36814336 -17.17349886]
89.2132883942747
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([1.  , 0.75]), array([1.  , 0.75])]
hi
[0.         0.22909838 0.

[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ]), array([0.125, 1.   ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]

[[13.03590441 29.43298999]
 [18.2333679  29.43298999]
 [23.43083139 29.43298999]
 [32.         29.43298999]]

[0.12625 0.7715 ]

[21.67502593 29.43298999]
center
[-21.54877593 -28.66148999]
57.64448607568215
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([1.  , 0.75]), array([1.  , 0.75])]
hi
[0.         0.22909838 0.22909838 0.22909838 0.6153

[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ]), array([0.125, 1.   ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]
hi
[0.         0.21205787 0.72315332 0.92411001 0.92411001 1.
 1.         1.        ]
frac prog
8
[0.         0.21205787 0.72315332 0.92411001 0.92411001 1.
 1.         1.        ]
start stroke error
[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ]), array([0.125, 1.   ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]

[[30.55393656 18.95191849]
 [25.35647307 18.95191849]
 [23.12737483 14.99488774]
 [14.55820622 14.99488774]]

[0.12625 0.7715 ]

[23.39899767 16.97340312]
center
[-23.27274767 -16.20190312]
48.776947787496034
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), a

54.74912787466478
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ])]
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([1.  , 0.75]), array([1.  , 0.75])]
hi
[0.         0.22909838 0.22909838 0.22909838 0.61530666 0.68277787
 0.68277787 0.91187625 0.91187625 0.91187625 1.         1.        ]
frac prog
12
[0.         0.22909838 0.22909838 0.22909838 0.61530666 0.68277787
 0.68277787 0.91187625 0.91187625 0.91187625 1.         1.        ]
start stroke error
[array([0., 0.]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.  , 0.95]), array

[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4]), array([0.5, 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([0.9, 0.7]), array([0.4, 1. ])]
hi
[0.         0.24524465 0.24524465 0.24524465 0.42803922 0.42803922
 0.42803922 0.63240976 0.63240976 0.63240976 0.76166504 1.        ]
frac prog
12
[0.         0.24524465 0.24524465 0.24524465 0.42803922 0.42803922
 0.42803922 0.63240976 0.63240976 0.63240976 0.76166504 1.        ]
start stroke error
[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4]), array([0.5, 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([0.9, 0.7]), array([0.4, 1. ])]

[[ 9.10995074 25.16806856]
 [ 5.30378093 20.0714346 ]
 [ 5.30378093  8.18789871]
 [ 5.30378093  3.81619017]]

[0.66666667 0.34166667]

[ 6.25532339 14.31089801]
center
[ -5.58865672 -13.96923135]
49.68971965045824
[array([0., 0.]), arra


[0.50277778 0.46666667]

[18.21137969  2.70485666]
center
[-17.70860191  -2.23818999]
98.29928930944348
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683])]
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.324, 0.863]), array([0.118, 1.   ]), array([0., 1.])]
hi
[0.         0.55600817 0.55600817 0.55600817 0.55600817 0.7025426
 0.90394002 1.        ]
frac prog
8
[0.         0.55600817 0.55600817 0.55600817 0.55600817 0.7025426
 0.90394002 1.        ]
start stroke error
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.324, 0.863]), array([0.118, 1.   ]), array([0., 1.])]

[[ 6.80139206  6.18252951]
 [ 9.10995074  3.09126476]
 [12.37474575  3.09126476]
 [15.63954075  3.09126476]
 [21.02227771  3.09126476]
 [24.28707272  3.09126476]
 [26.5956314   0.        ]
 [29.8604264   0.        ]]

[0.257125 0


[0.5 0.5]

[17.63096941 17.68155143]
center
[-17.13096941 -17.18155143]
49.905725728641265
[array([0., 0.]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95])]
[array([0., 0.]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0., 1.]), array([0.05, 1.  ]), array([0.05, 1.  ])]
[array([0., 0.]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0., 1.]), array([0.05, 1.  ]), array([0.05, 1.  ]), array([0.05, 1.  ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ])]
[array([0., 0.]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0.  , 0.95]), array([0., 1.]), array([0.05, 1.  ]), array([0.05, 1.  ]), array([0.05, 1.  ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.9, 1. ]), array([0.984, 0.99 ]), array([0.99 , 0.855]), array([1. , 0.7])]
hi
[0.         0.41757349 0.41757349 0.41757349 0.41757349 0.43955104
 0.46152859 0.46152859 0.46152859 

[0.75 0.25]

[22.41177438 32.        ]
center
[-21.66177438 -31.75      ]
21.967351834569936
[array([0.2, 0. ]), array([0.475, 0.313]), array([0.526, 1.   ]), array([0., 1.])]
hi
[0.         0.2553704  0.67760452 1.        ]
frac prog
4
[0.         0.2553704  0.67760452 1.        ]
start stroke error
[array([0.2, 0. ]), array([0.475, 0.313]), array([0.526, 1.   ]), array([0., 1.])]

[[12.24823245 32.        ]
 [21.12286538 32.        ]
 [26.50560234 32.        ]
 [29.77039735 32.        ]]

[0.30025 0.57825]

[22.41177438 32.        ]
center
[-22.11152438 -31.42175   ]
22.844062829991543
[array([0., 0.]), array([0. , 0.5])]
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5])]
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1., 1.])]
hi
[0.   0.25 0.25 0.75 0.75 1.  ]
frac prog
6
[0.   0.25 0.25 0.75 0.75 1.  ]
start stroke error
[array([0., 0.]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1.

[-20.33455414 -19.38146411]
49.57118372622046
[array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]
hi
[0.         0.49406752 1.        ]
frac prog
3
[0.         0.49406752 1.        ]
start stroke error
[array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]

[[32.         20.11646411]
 [23.12536707 20.11646411]
 [17.74263011 20.11646411]
 [ 8.86799718 20.11646411]]

[0.54996506 0.55430712]

[20.43399859 20.11646411]
center
[-19.88403353 -19.56215699]
27.35604720520716
[array([1, 0]), array([0, 1])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([1, 0]), array([0, 1])]

[[32.         20.11646411]
 [23.12536707 20.11646411]
 [17.74263011 20.11646411]
 [ 8.86799718 20.11646411]]

[0.5 0.5]

[20.43399859 20.11646411]
center
[-19.93399859 -19.61646411]
27.309877786989098
[array([0, 0]), array([1, 0])]
[array([0, 0]), array([1, 0]), array([1, 0]), array([1, 1])]
hi
[0.  0.5 0.5 1. ]
frac prog
4
[0.  0.5 0.5 1. ]
start stroke error
[array([0, 0]), array([

40.42143730831606
[array([0., 0.]), array([0.5, 0. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([1. , 0.5])]
hi
[0.         0.22654092 0.22654092 0.67962276 0.67962276 1.        ]
frac prog
6
[0.         0.22654092 0.22654092 0.67962276 0.67962276 1.        ]
start stroke error
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([1. , 0.5])]

[[14.86521788 32.        ]
 [10.74346784 28.10238645]
 [10.74346784 24.75915432]
 [ 6.62171781 20.86154077]
 [ 2.49996777 16.96392722]
 [ 0.         14.59990511]]

[0.5        0.41666667]

[ 7.57897319 22.88115231]
center
[ -7.07897319 -22.46448564]
40.53912418132618
[array([0., 0.]), array([0.1, 0.9]), array([0.2, 1. ])]
[array([0., 0.]), array([0.1, 0.9]), array([0.2, 1. ]), array([0.2, 1. ]), array([0.3, 0.8]), array([0.3, 0.8])]
hi
[0.         0.71270445 0.82401018


[ 7.57897319 22.88115231]
center
[ -7.32897319 -22.13115231]
40.52747442496785
g_points
5
[[ 7.1104859  22.47598516]
 [ 7.1104859  16.96392722]
 [ 9.61045367 14.59990511]
 [ 9.61045367  9.08784717]
 [ 9.61045367  0.        ]]

[0.         0.23403116 0.38011668 0.61414784 1.        ]
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]

[[ 7.1104859  22.47598516]
 [ 7.1104859  16.96392722]
 [ 9.61045367 14.59990511]
 [ 9.61045367  9.08784717]
 [ 9.61045367  0.        ]]

[0.5 0.5]

[ 8.61046656 12.62553293]
center
[ -8.11046656 -12.12553293]
32.2162618008687
[array([0, 1]), array([1, 1])]
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]
hi
[0.  0.5 0.5 1. ]
frac prog
4
[0.  0.5 0.5 1. ]
start stroke error
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]

[[ 7.1104859  22.47598516]
 [ 7.1104859  16.96392722]
 [ 9.61045367 14.59990511]


[0.50277778 0.46666667]

[ 8.61046656 12.62553293]
center
[ -8.10768878 -12.15886627]
84.55402863334527
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683])]
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.324, 0.863]), array([0.118, 1.   ]), array([0., 1.])]
hi
[0.         0.55600817 0.55600817 0.55600817 0.55600817 0.7025426
 0.90394002 1.        ]
frac prog
8
[0.         0.55600817 0.55600817 0.55600817 0.55600817 0.7025426
 0.90394002 1.        ]
start stroke error
[array([0.323, 0.   ]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.323, 0.683]), array([0.324, 0.863]), array([0.118, 1.   ]), array([0., 1.])]

[[ 7.1104859  22.47598516]
 [ 7.1104859  16.96392722]
 [ 9.61045367 14.59990511]
 [ 9.61045367  9.08784717]
 [ 9.61045367  0.        ]]

[0.257125 0.699375]

[ 8.61046656 12.62553293]
center
[ -8.35334156 -11.92615793]
38.9080822

[array([0., 0.]), array([0.6, 0. ]), array([0.6, 0. ]), array([0.85, 1.  ]), array([0.85, 1.  ]), array([1.  , 0.75])]

[[13.73220371  2.51280145]
 [19.56123851  2.51280145]
 [23.09672684  2.51280145]
 [25.59669461  4.87682357]
 [29.13218293  4.87682357]]

[0.65       0.45833333]

[22.22380932  3.4584103 ]
center
[-21.57380932  -3.00007697]
28.290069566662083
[array([0., 1.]), array([1.09574468, 0.87209302]), array([1.01595745, 0.49418605]), array([1., 0.])]
hi
[0.         0.5560782  0.75076766 1.        ]
frac prog
4
[0.         0.5560782  0.75076766 1.        ]
start stroke error
[array([0., 1.]), array([1.09574468, 0.87209302]), array([1.01595745, 0.49418605]), array([1., 0.])]

[[13.73220371  2.51280145]
 [19.56123851  2.51280145]
 [23.09672684  2.51280145]
 [25.59669461  4.87682357]
 [29.13218293  4.87682357]]

[0.77792553 0.59156977]

[22.22380932  3.4584103 ]
center
[-21.44588379  -2.86684053]
22.52534881142032
[array([0., 0.]), array([0.6, 0. ]), array([0.6, 0. ])]
[array([0., 

[array([0.        , 0.56139228]), array([1.        , 0.43860772])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.        , 0.56139228]), array([1.        , 0.43860772])]

[[20.43942401  2.05061206]
 [20.43942401  5.3938442 ]
 [20.43942401 14.48169137]
 [20.43942401 23.56953854]]

[0.5 0.5]

[20.43942401 11.37392154]
center
[-19.93942401 -10.87392154]
30.466885184239683
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75])]
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.075, 0.925]), array([0., 1.])]
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.075, 0.925]), array([0., 1.]), array([0., 1.]), array([0.25, 0.72]), array([0.25, 0.72])]
hi
[0.         0.53323705 0.53323705 0.53323705 0.6577098  0.73312091
 0.73312091 1.         1.        ]
frac prog
9
[0.         0.53323705 0.53323705 0.53323705 0.6577098  0.73312091
 0.73312091 1.         1.        ]
start stroke error
[ar

[-22.54939965 -20.46454507]
25.28537982936959
[array([0., 0.]), array([0.5, 0. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.5])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.5]), array([0.5, 0.5]), array([1. , 0.5])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.5]), array([0.5, 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1., 1.])]
hi
[0.   0.25 0.25 0.5  0.5  0.75 0.75 1.  ]
frac prog
8
[0.   0.25 0.25 0.5  0.5  0.75 0.75 1.  ]
start stroke error
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.5]), array([0.5, 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1., 1.])]

[[16.31767397 20.96454507]
 [19.8531623  20.96454507]
 [25.6821971  20.96454507]
 [31.51123191 20.96454507]]

[0.625 0.375]

[23.34106632 20.96454507]
center
[-22.71606632 -20.58954507]
27.85638994093431
[array([0.        , 0.56139228]), array([1.        , 0.43860772])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stro

[0.         0.30719589 0.81367628 1.        ]
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]

[[32.         11.55487358]
 [26.1709652  11.55487358]
 [16.56051153 11.55487358]
 [13.0250232  11.55487358]]

[0.5 0.5]

[21.93912498 11.55487358]
center
[-21.43912498 -11.05487358]
27.089915279706304
[array([0, 1]), array([1, 1])]
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]
hi
[0.  0.5 0.5 1. ]
frac prog
4
[0.  0.5 0.5 1. ]
start stroke error
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]

[[32.         11.55487358]
 [26.1709652  11.55487358]
 [16.56051153 11.55487358]
 [13.0250232  11.55487358]]

[0.75 0.75]

[21.93912498 11.55487358]
center
[-21.18912498 -10.80487358]
26.997185447714322
[array([0., 0.]), array([1., 0.])]
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([1., 1.])]
[array([0., 0.]), array([1., 0.]), ar

8
[0.         0.24116279 0.37289138 0.48623032 0.48623032 0.594747
 0.78584318 1.        ]
start stroke error
[array([0.278, 0.021]), array([0.152, 0.348]), array([0.068, 0.52 ]), array([0.  , 0.67]), array([0.  , 0.67]), array([0.156, 0.693]), array([0.418, 0.785]), array([0.678, 0.956])]

[[32.         11.55487358]
 [26.1709652  11.55487358]
 [16.56051153 11.55487358]
 [13.0250232  11.55487358]]

[0.21875  0.582875]

[21.93912498 11.55487358]
center
[-21.72037498 -10.97199858]
33.234310200124774
[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ])]
[array([0., 0.]), array([0.304, 0.172]), array([0.456, 1.   ]), array([0.125, 1.   ]), array([0.125, 1.   ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]
hi
[0.         0.21205787 0.72315332 0.92411001 0.92411001 1.
 1.         1.        ]
frac prog
8
[0.         0.21205787 0.72315332 0.92411001 0.92411001 1.
 1.         1.        ]
start stroke error
[array([0., 0.]), array([0.304, 0.172]), array([0

6
[0.         0.73879613 0.73879613 0.73879613 0.8850703  1.        ]
start stroke error
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]), array([0.86, 0.14]), array([0.75, 0.25])]

[[29.024092   10.87399447]
 [24.76936797 14.88418884]
 [20.51464395 18.89438321]
 [20.51464395 22.33418312]]

[0.76833333 0.065     ]

[23.70568697 16.74668741]
center
[-22.93735363 -16.68168741]
22.10722704413982
[array([0.22501403, 0.        ]), array([0.5, 0. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 1.        ])]
hi
[0.         0.17741351 0.17741351 0.82258649 0.82258649 1.        ]
frac prog
6
[0.         0.17741351 0.17741351 0.82258649 0.82258649 1.        ]
start stroke error
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597,

[array([0., 1.]), array([0.3, 0.8]), array([0.3, 0. ])]
hi
[0.         0.31067471 1.        ]
frac prog
3
[0.         0.31067471 1.        ]
start stroke error
[array([0., 1.]), array([0.3, 0.8]), array([0.3, 0. ])]

[[28.16824472 22.33418312]
 [24.51869611 22.33418312]
 [14.59819444 22.33418312]
 [ 8.58110602 22.33418312]]

[0.2 0.6]

[18.96656032 22.33418312]
center
[-18.76656032 -21.73418312]
29.24022092265813
[array([0.05555556, 0.        ]), array([0.5, 0. ])]
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 0.72501403])]
hi
[0.         0.24242424 0.24242424 0.78787879 0.78787879 1.        ]
frac prog
6
[0.         0.24242424 0.24242424 0.78787879 0.78787879 1.        ]
start stroke error
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.7749859

frac prog
12
[0.         0.18058037 0.18058037 0.18058037 0.77160081 0.77160081
 0.77160081 0.83214458 0.88508857 0.88508857 1.         1.        ]
start stroke error
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.77498597, 1.        ]), array([0.77498597, 1.        ])]

[[19.67117464 29.01294845]
 [17.09055407 26.58064261]
 [17.09055407 20.90937135]
 [17.09055407 15.23810008]
 [12.83583004 11.2279057 ]
 [ 9.18628143 11.2279057 ]]

[0.54124883 0.64083333]

[15.49415806 19.03281232]
center
[-14.95290922 -18.39197898]
84.46297015777257
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0.294, 0.841]), array([0.624, 0.494]), array([0.846, 0.005])]
hi
[0.         0.15689364 0.15689364 0.15689364 0.15689

[array([0.3, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([0.79 , 0.783]), array([0.344, 0.976]), array([0., 1.])]

[[ 6.14190824  2.5154942 ]
 [12.15899666  2.5154942 ]
 [22.07949833  2.5154942 ]
 [32.          2.5154942 ]]

[0.45283333 0.56325   ]

[18.09510081  2.5154942 ]
center
[-17.64226748  -1.9522442 ]
65.61138327839382
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.95, 1.  ]

[0.         0.23485499 0.23485499 0.23485499 0.65759397 0.65759397
 0.65759397 0.70089909 0.73876832 0.73876832 0.90316681 0.90316681
 0.90316681 1.         1.        ]
frac prog
15
[0.         0.23485499 0.23485499 0.23485499 0.65759397 0.65759397
 0.65759397 0.70089909 0.73876832 0.73876832 0.90316681 0.90316681
 0.90316681 1.         1.        ]
start stroke error
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.95, 1.  ]), array([0.95, 1.  ]), array([0.95, 1.  ]), array([1. , 0.8]), array([1. , 0.8])]

[[30.32589654  4.09338274]
 [30.32589654 13.44372831]
 [26.07117252 17.45392268]
 [30.32589654 21.46411705]
 [27.74527597 23.89642289]
 [27.74527597 29.56769416]
 [17.82477431 29.56769416]
 [15.24415373 32.        ]
 [11.59460512 32.        ]
 [ 1.67410346 32.        ]]

[0.638 0.686]

[21.88770507 23.5486962 ]
center
[-21.24970507 -22


[0.544      0.56258333]

[21.88770507 23.5486962 ]
center
[-21.34370507 -22.98611287]
144.97801891586474
[array([0. , 0.5]), array([1. , 0.5])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0. , 0.5]), array([1. , 0.5])]

[[30.32589654  4.09338274]
 [30.32589654 13.44372831]
 [26.07117252 17.45392268]
 [30.32589654 21.46411705]
 [27.74527597 23.89642289]
 [27.74527597 29.56769416]
 [17.82477431 29.56769416]
 [15.24415373 32.        ]
 [11.59460512 32.        ]
 [ 1.67410346 32.        ]]

[0.5 0.5]

[21.88770507 23.5486962 ]
center
[-21.38770507 -23.0486962 ]
116.2613591542251
[array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.3, 1. ])]
hi
[0.         0.83333333 0.83333333 1.        ]
frac prog
4
[0.         0.83333333 0.83333333 1.        ]
start stroke error
[array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.3, 1. ])]

[[30.32589654  4.09338274]
 [30.32589654 13.44372831]
 [26.07117252 17.45392268]
 [

[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.5, 1. ]), array([0.5, 0. ])]

[[ 1.67410346 27.13538832]
 [ 1.67410346 21.46411705]
 [ 4.25472403 19.03181122]
 [ 0.         15.02161684]
 [ 0.          5.67127127]
 [ 0.          0.        ]]

[0.5 0.5]

[ 1.26715516 14.72070078]
center
[ -0.76715516 -14.22070078]
47.86251766206075
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5])]
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5])]
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([0.94 , 0.984]), array([0.868, 0.917]), array([0.52, 0.85])]
hi
[0.         0.21723451 0.21723451 0.21723451 0.21723451 0.62062887
 0.62062887 0.62062887 0.62062887 0.81736625 0.85704066 1.        ]
frac prog
12
[0.         0.21723451 0.21723451 0.217

[-23.87754832 -13.99265626]
24.667289585851854
[array([0.38, 0.  ]), array([0.38, 1.  ]), array([0., 1.])]
hi
[0.         0.72463768 1.        ]
frac prog
3
[0.         0.72463768 1.        ]
start stroke error
[array([0.38, 0.  ]), array([0.38, 1.  ]), array([0., 1.])]

[[29.46708191  7.68097719]
 [25.20115504 12.4685065 ]
 [20.93522816 17.25603581]
 [20.93522816 21.36260555]]

[0.25333333 0.66666667]

[24.13467332 14.69203126]
center
[-23.88133999 -14.02536459]
21.471865258447618
[array([1., 0.]), array([0.756, 0.732]), array([0., 1.])]
hi
[0.         0.49030894 1.        ]
frac prog
3
[0.         0.49030894 1.        ]
start stroke error
[array([1., 0.]), array([0.756, 0.732]), array([0., 1.])]

[[29.46708191  7.68097719]
 [25.20115504 12.4685065 ]
 [20.93522816 17.25603581]
 [20.93522816 21.36260555]]

[0.58533333 0.57733333]

[24.13467332 14.69203126]
center
[-23.54933999 -14.11469793]
21.17383791890313
[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ])]
[array([0.1, 0. ]), 


[0.54124883 0.64083333]

[23.31538273 21.75790984]
center
[-22.7741339 -21.1170765]
60.373378640446376
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0.294, 0.841]), array([0.624, 0.494]), array([0.846, 0.005])]
hi
[0.         0.15689364 0.15689364 0.15689364 0.15689364 0.36561374
 0.66464404 1.        ]
frac prog
8
[0.         0.15689364 0.15689364 0.15689364 0.15689364 0.36561374
 0.66464404 1.        ]
start stroke error
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0.294, 0.841]), array([0.624, 0.494]), array([0.846, 0.005])]

[[30.37598592 21.75790984]
 [26.71682791 21.75790984]
 [23.0576699  21.75790984]
 [13.11104718 21.75790984]]

[0.223625 0.76125 ]

[23.31538273 21.75790984]
center
[-23.09175773 -20.99665984]
37.70833452038641
[array([0., 0.]), array([0.  , 0.75]), array([0.  , 0.75])]
[array([0., 

[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.77498597, 1.        ]), array([0.77498597, 1.        ])]

[[23.1585738  27.56547646]
 [20.57115836 24.66169315]
 [23.1585738  21.75790984]
 [18.89264693 16.97038053]
 [16.30523149 14.06659721]
 [12.03930461  9.2790679 ]]

[0.54124883 0.64083333]

[19.02091483 19.05018751]
center
[-18.479666   -18.40935418]
80.11289567685849
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.])]
[array([0.025, 0.75 ]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0., 1.]), array([0.294, 0.841]), array([0.624, 0.494]), array([0.846, 0.005])]
hi
[0.         0.15689364 0.15689364 0.15689364 0.15689364 0.36561374
 0.66464404 1.        ]
frac prog
8
[0.         0.15689364 0.15689364 0.15689364 0.15689364 0.36561374
 0.66464404 1.        ]
start stroke error
[array

82.83180442756188
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.95, 1.  ]), array([0.95, 1.  ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.5, 0.9]), array([0.52, 0.99]), array([0.6, 1. ]), array([0.6, 1. ]), array([0.95, 1.  ]), array([0.95, 1.  ]), array([0.95, 1.  ]), array([1. , 0.8]), array([1. , 0.8])]
hi
[0.         0.23485499 0.23485499 0.23485499 0.65759397 0.65759397
 0.65759397 0.70089909 0.73876832 0.73876832 0

[array([0., 0.]), array([0.3, 0.8]), array([1., 1.])]

[[32.          0.        ]
 [32.         11.1628139 ]
 [32.         22.32562781]
 [32.         29.09621669]
 [29.41258456 32.        ]
 [19.46596183 32.        ]
 [15.80680382 32.        ]
 [ 5.8601811  32.        ]]

[0.43333333 0.6       ]

[24.81819141 23.8230823 ]
center
[-24.38485808 -23.2230823 ]
107.265689056318
[array([0., 0.]), array([0.5, 0. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([1. , 0.5])]
hi
[0.         0.22654092 0.22654092 0.67962276 0.67962276 1.        ]
frac prog
6
[0.         0.22654092 0.22654092 0.67962276 0.67962276 1.        ]
start stroke error
[array([0., 0.]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([1. , 0.5])]

[[32.          0.        ]
 [32.         11.1628139 ]
 [32.         22.32562781]
 [32.         29.09621669]
 [29.41

6
[[ 9.21720397 32.        ]
 [ 6.62978852 29.09621669]
 [ 6.62978852 17.93340279]
 [ 2.36386165 13.14587347]
 [ 6.62978852  8.35834416]
 [ 6.62978852  4.25177442]]

[0.         0.12160365 0.47062221 0.67111273 0.87160325 1.        ]
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.        , 0.75476272]), array([1.        , 0.24523728])]

[[ 9.21720397 32.        ]
 [ 6.62978852 29.09621669]
 [ 6.62978852 17.93340279]
 [ 2.36386165 13.14587347]
 [ 6.62978852  8.35834416]
 [ 6.62978852  4.25177442]]

[0.5 0.5]

[ 6.35003662 17.46426859]
center
[ -5.85003662 -16.96426859]
54.48845915715983
[array([0, 1]), array([1, 1])]
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]
hi
[0.  0.5 0.5 1. ]
frac prog
4
[0.  0.5 0.5 1. ]
start stroke error
[array([0, 1]), array([1, 1]), array([1, 1]), array([1, 0])]

[[ 9.21720397 32.        ]
 [ 6.62978852 29.09621669]
 [ 6.62978852 17.93340279]
 [ 2.36386165 13.14587

[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4])]
[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4]), array([0.5, 0.4]), array([1. , 0.4]), array([1. , 0.4])]
[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4]), array([0.5, 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([0.9, 0.7]), array([0.4, 1. ])]
hi
[0.         0.24524465 0.24524465 0.24524465 0.42803922 0.42803922
 0.42803922 0.63240976 0.63240976 0.63240976 0.76166504 1.        ]
frac prog
12
[0.         0.24524465 0.24524465 0.24524465 0.42803922 0.42803922
 0.42803922 0.63240976 0.63240976 0.63240976 0.76166504 1.        ]
start stroke error
[array([0.1, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.7, 0. ]), array([0.5, 0.4]), array([0.5, 0.4]), array([0.5, 0.4]), array([1. , 0.4]), array([1. , 0.4]), array([

[array([0., 1.]), array([0.3, 0.8]), array([0.3, 0. ])]

[[23.97784784  9.36021408]
 [19.08622486 14.01435412]
 [14.89036732 14.01435412]
 [14.89036732 20.59630208]]

[0.2 0.6]

[18.21120183 14.4963061 ]
center
[-18.01120183 -13.8963061 ]
18.125929692283837
[array([0.05555556, 0.        ]), array([0.5, 0. ])]
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 0.72501403])]
hi
[0.         0.24242424 0.24242424 0.78787879 0.78787879 1.        ]
frac prog
6
[0.         0.24242424 0.24242424 0.78787879 0.78787879 1.        ]
start stroke error
[array([0.05555556, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 0.72501403])]

[[23.97784784  9.36021408]
 [19.08622486 14.01435412]
 [14.89036732 14.01435412]
 [14.89036732 20.59630208]]

[0.47175692 0.45416901]

[18.21

[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.075, 0.925]), array([0., 1.]), array([0., 1.]), array([0.25, 0.72]), array([0.25, 0.72])]

[[24.67361329 22.13981961]
 [17.75581372 22.13981961]
 [10.83801416 22.13981961]
 [ 6.64215663 22.13981961]]

[0.09944444 0.735     ]

[14.97739945 22.13981961]
center
[-14.87795501 -21.40481961]
32.20626709380276
[array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]
hi
[0.         0.49406752 1.        ]
frac prog
3
[0.         0.49406752 1.        ]
start stroke error
[array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]

[[24.67361329 22.13981961]
 [17.75581372 22.13981961]
 [10.83801416 22.13981961]
 [ 6.64215663 22.13981961]]

[0.54996506 0.55430712]

[14.97739945 22.13981961]
center
[-14.42743439 -21.5855125 ]
23.6026831670499
[array([1, 0]), array([0, 1])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([1, 0]), array([0, 1])]

[[24.67361329 22.13981961]
 [17.75

center
[-12.32811111 -13.33845188]
54.430982197867465
[array([0.        , 0.56139228]), array([1.        , 0.43860772])]
hi
[0. 1.]
frac prog
2
[0. 1.]
start stroke error
[array([0.        , 0.56139228]), array([1.        , 0.43860772])]

[[15.92003042 28.24093067]
 [15.92003042 17.38913306]
 [15.92003042 13.39697982]
 [12.95311111 10.5741012 ]
 [ 9.98619179  7.75122257]
 [ 7.01927248  4.92834395]]

[0.5 0.5]

[12.95311111 13.71345188]
center
[-12.45311111 -13.21345188]
42.60126597711171
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75])]
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.075, 0.925]), array([0., 1.])]
[array([0.08, 0.  ]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.08, 0.75]), array([0.075, 0.925]), array([0., 1.]), array([0., 1.]), array([0.25, 0.72]), array([0.25, 0.72])]
hi
[0.         0.53323705 0.53323705 0.53323705 0.6577098  0.73312091
 0.73312091 1.         1.        ]
frac prog
9
[0.         0.533

3
[0.         0.49406752 1.        ]
start stroke error
[array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]

[[ 4.29733045  0.        ]
 [15.70285373  0.        ]
 [20.59447671  4.65414004]
 [32.          4.65414004]]

[0.54996506 0.55430712]

[18.14866522  2.32707002]
center
[-17.59870016  -1.7727629 ]
34.02364641672294
[array([0.22501403, 0.        ]), array([0.5, 0. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ])]
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 0.72501403])]
hi
[0.         0.16526842 0.16526842 0.76627516 0.76627516 1.        ]
frac prog
6
[0.         0.16526842 0.16526842 0.76627516 0.76627516 1.        ]
start stroke error
[array([0.22501403, 0.        ]), array([0.5, 0. ]), array([0.5, 0. ]), array([0.5, 1. ]), array([0.5, 1. ]), array([0.77498597, 0.72501403])]

[[ 4.29733045  0.        ]
 [15.70285373  0.        ]
 [20.5

frac prog
6
[0.         0.42488945 0.42488945 0.8497789  0.8497789  1.        ]
start stroke error
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([1., 1.]), array([1., 1.]), array([0.75, 0.75])]

[[25.4860997   0.        ]
 [25.4860997   3.99215324]
 [25.4860997  10.5741012 ]
 [25.4860997  14.56625444]
 [25.4860997  21.1482024 ]
 [25.4860997  32.        ]
 [21.29024216 32.        ]
 [14.3724426  32.        ]
 [ 2.96691931 32.        ]]

[0.79166667 0.45833333]

[21.28291136 19.80896792]
center
[-20.49124469 -19.35063459]
118.3019455101342
[array([0.2, 0. ]), array([0.  , 0.55]), array([0.  , 0.55]), array([0.  , 0.55])]
[array([0.2, 0. ]), array([0.  , 0.55]), array([0.  , 0.55]), array([0.  , 0.55]), array([0.02, 0.5 ]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5])]
[array([0.2, 0. ]), array([0.  , 0.55]), array([0.  , 0.55]), array([0.  , 0.55]), array([0.02, 0.5 ]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([0.94 , 0.984]

frac prog
2
[0. 1.]
start stroke error
[array([0.5, 1. ]), array([0.5, 0. ])]

[[25.4860997   0.        ]
 [25.4860997   3.99215324]
 [25.4860997  10.5741012 ]
 [25.4860997  14.56625444]
 [25.4860997  21.1482024 ]
 [25.4860997  32.        ]
 [21.29024216 32.        ]
 [14.3724426  32.        ]
 [ 2.96691931 32.        ]]

[0.5 0.5]

[21.28291136 19.80896792]
center
[-20.78291136 -19.30896792]
116.90031629548665
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5])]
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5])]
[array([0.2, 0. ]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([0. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([1. , 0.5]), array([0.94 , 0.984]), array([0.868, 0.917]), array([0.52, 0.85])]
hi
[0.         0.21723451 0.21723451 0.21723451 0.21723451 0.62062887
 0.62062887 0.62062887 0.62062887 0.81736625 0

[array([0., 0.]), array([1., 0.]), array([1., 0.])]
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]
hi
[0.         0.25667245 0.25667245 0.61966212 0.80757471 1.        ]
frac prog
6
[0.         0.25667245 0.25667245 0.61966212 0.80757471 1.        ]
start stroke error
[array([0., 0.]), array([1., 0.]), array([1., 0.]), array([0., 1.]), array([0.64989518, 0.66292135]), array([1., 0.])]

[[ 4.19585753 29.17712137]
 [ 4.19585753 22.59517341]
 [ 0.         22.59517341]
 [ 0.         16.01322545]
 [ 0.          9.43127749]
 [ 4.89162298  4.77713746]
 [ 0.          0.12299742]]

[0.60831586 0.27715356]

[ 1.89761972 14.95887229]
center
[ -1.28930386 -14.68171873]
62.09976223262809
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.65, 0.  ]), array([0.3, 0.5]), array([0.3, 0.5])]
[array([0., 0.]), array([0.65, 0.  ]), array([0.65, 0.  ]), array